// © 2005 IDesign Inc. All rights reserved 
//Questions? Comments? go to 
//http://www.idesign.net

//This file was generated by using WSDL.exe /serverInterface and then cleaning up the generated interface definition

using System;

public interface IUserManager
{
   bool Authenticate(string applicationName,string userName,string password);
   bool IsInRole(string applicationName,string userName,string role);
   string[] GetRoles(string applicationName,string userName);
}

